### ISSUE TITLE
data-lux-form-identification="true TYPO3 10

### ISSUE THREAD

**Issue by fritzdacat** [in2code-de/lux#36]
I added "data-lux-form-identification="true" to a TYPO3 form_framework forumlar in TYPO3 10.4.36 & Lux 26.4.2 because I only want the lead to be tracked when the form has been submitted.

https://github.com/in2code-de/lux/blob/develop/Documentation/Technical/Identification/Index.md#2-formfieldmapping

However, if you now fill out the form and send it off, the page with the form is loaded again and not the "Thank you" page. An email is not sent either.

If I remove "data-lux-form-identification="true" from the form again, the form works perfectly.

in TYPO3 11.5.26 & LUX 30.1.0 this seems to work fine....

**Comment by einpraegsam** [comment]
Hi, at the moment we're able to fix issues for TYPO3 11 and 12 very fast. But for 10 there is no test environment. We are working on that issue.

**Comment by einpraegsam** [comment]
So, I spent a few hours into that issue to find the problem.
"typo3/cms-form" needs a `submitButton.click()` instead of `form.submit()` because the submitbutton itself tells the form where to (for multistep forms).

So, there are two new LUX versions (26.5.0 for TYPO3 10/11 and 31.1.0 for TYPO3 11/12) that support `data-lux-form-identification="submitButton"` that can be used to click on submit instead of submitting the form itself (see https://github.com/in2code-de/lux/blob/develop/Documentation/Technical/Identification/Index.md#2-formfieldmapping for details).

**Comment by fritzdacat** [comment]
Works in TYPO3 10 & 11. Thanks for the quick fix!
