### ISSUE TITLE
OrderBy categoryscorings.scoring causes SQL error in lead list

### ISSUE THREAD

**Issue by ffellbaum** [in2code-de/lux#60]
Selecting a categoryScoring in Lead list causes SQL error "Expression #2 of ORDER BY clause is not in SELECT list, references column 'hydac.tx_lux_domain_model_categoryscoring.scoring' which is not in SELECT list; this is incompatible with DISTINCT"

Class: In2code\Lux\Domain\Repository\VisitorRepository

Functions: findAllWithIdentifiedFirst() / getOrderingsArrayByFilterDto()

**Comment by einpraegsam** [comment]
Thx for reporting.
Can you pls report some more information like TYPO3 version, LUX version, MySQL version, SQL mode and where I exactly have to click in backend to reproduce this error?

**Comment by ffellbaum** [comment]
TYPO3 Version: 12.4.22
LUX: 36.4.0 (with LUX Enterprise 43.0.0)
PHP 8.2.x
MySQL 8

In TYPO3 Backend, go to module LUX Leads, Click Button Leads (Button Bar Dashboard, Leads, Companies), than select filter categoryScoring, submit by button filter now (see ![lux](https://github.com/user-attachments/assets/523dce6d-582c-4f49-b65c-e55a27c9d050) )

**Comment by einpraegsam** [comment]
Hmm, played a bit but cannot reproduce this issue. This is maybe related to the fact that we are using MariaDB instead of MySQL. I will dig deaper...

**Comment by einpraegsam** [comment]
Okay, as long as we use extbase for the query here, there is a problem when trying to order by `categoryscorings.scoring DESC` because MySQL (5 and 8) expects this value also in the select field list. But we cannot manipulate the select fields in extbase. That's quite funny, because MariaDB 10 works fine here.

It's a pitty, but a general orderings by categoryscoring descending isn't possible in the short run any more here.

**Comment by einpraegsam** [comment]
I just released 36.5.1 which fixes this issue.

But, sorting by categoryscoring isn't possible any more at the moment.

**Comment by ffellbaum** [comment]
Thank you very much for fixing this issue so fast!
